# Generated by Django 5.0.7 on 2024-07-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_img',
            name='content',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
